Add some new kaomojis.
xuezhma/kaomoji-typer pull request #12
Opened 2017-04-08 01:51 UTC by xingmarc

2017-04-13 00:21 UTC, xuezhma requested changes

2017-04-13 00:21 UTC, xuezhma commented on js/kaomoji-collection.js
> +        "angry": [
I'd recommend to tag this list as `angry middle finger fuck` since all of them are pointing the finger

2017-04-13 00:21 UTC, xuezhma commented on js/kaomoji-collection.js
> +        "christmas": [
let's add `xmas` to the tag too

2017-04-13 00:24 UTC, xuezhma commented
Thanks for the pr. There are a couple changes might be good to make. Please see my comments.

2017-04-14 22:35 UTC, xingmarc commented
Changed.

2017-04-14 23:38 UTC, xuezhma approved these changes

2017-04-14 23:38 UTC, merged